---
title: "ampelos"
output: github_document
---


```{r, echo=FALSE, message=F, warning=F}
# https://tex.stackexchange.com/questions/152488/suppress-library-comments-from-output-with-knitr

##################### QA #############################
# QA : bugs.df %>% dplyr::group_by(julian) %>% skim() 
# bugs.df %>% dplyr::filter(julian==158) %>% skim() 
# https://stackoverflow.com/questions/22353633/filter-for-complete-cases-in-data-frame-using-dplyr-case-wise-deletion
# bugs.df %>% dplyr::filter(complete.cases(.))
# bugs.df %>% dplyr::filter(!complete.cases(.))
######################################################


suppressPackageStartupMessages(message("ABC"))

#setwd("./code/thesis/ampelos/")
source("./bug-library.R")

source.url <- c("https://raw.githubusercontent.com/cordphelps/ampelos/master/bugs.csv")
bugs.df <- read.csv(source.url, header=TRUE, row.names=NULL)

assign("bugs.df", bugs.df, envir=.GlobalEnv)

g <- compareTransect()
newFile <- paste("ampelos-", format(Sys.time(), "%d-%m-%Y-%H%M"), ".pdf", sep = "")
ggsave(file=newFile, g, width=20, height=30, device = "pdf", units = "cm") #saves g

# pass variables to dyplr pipes
# https://stackoverflow.com/questions/27975124/pass-arguments-to-dplyr-functions
plotSpeciesTrend(data=bugs.df, bugs=quo(Thomisidae..crab.spider.), speciesText="Crab Spider", where="control", when="pm", caption=Sys.Date())

plotRidges(data=bugs.df, combined=FALSE, bugs="Thomisidae..crab.spider.", speciesText="Crab Spider", where="control", when="pm", wk=1, caption=Sys.Date())

new.df <- bugs.df %>% mutate(newColumn = ifelse(Thomisidae..crab.spider. > 0, 1, 0))
plotRidges(data=new.df, combined=TRUE, bugs="newColumn", speciesText="Crab Spider", where="control", when="pm", wk=1, caption=Sys.Date())
plotRidges(data=new.df, combined=TRUE, bugs="newColumn", speciesText="Crab Spider", where="oakMargin", when="pm", wk=1, caption=Sys.Date())



total <- bugCount() 

print(total)


```






```{r kable, results='asis', echo=FALSE}

# kable(bugs.df, format = "html", booktabs = F, caption= "transpose prior")

# 'transpose' = swap rows and columns
bugsOnly.df <- t(bigTable(bugs.df))
# define a column name
colnames(bugsOnly.df)[1] <- "total"
# convert matrix to dataframe
bugsOnly.df <- data.frame(bugsOnly.df)
# add a new column
bugsOnly.df <- mutate(bugsOnly.df, new=total*5)

kable(bugsOnly.df, format = "html", booktabs = F, caption= "this is a caption") # %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

#bugsOnly.df %>% kable() %>% kable_styling() 
#kable(bugsOnly.df, ) %>%
#  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

```


