---
title: "ampelos V2"
output: github_document
# avoid background insertion of "TABLE X, FIGURE X" in output files
# https://stackoverflow.com/questions/31182147/how-to-suppress-automatic-table-name-and-number-in-an-rmd-file-using-xtable-or
#header-includes:
#    - \usepackage[labelformat=empty]{caption}
# that does not work
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results='hide')

# https://yihui.org/knitr/options/

# echo: (TRUE; logical or numeric) Whether to display the source code
# results: ('markup'; character) Controls how to display the text results.
# warning: (TRUE; logical) Whether to preserve warnings
# error: (TRUE; logical) Whether to preserve errors
# include: (TRUE; logical) Whether to include the chunk output in the output document.
# 
```

```{r localCode, echo=FALSE, include=FALSE}

source('/Users/rcphelps/code/thesis/ampelos/code/bayesNoClusters.R')

ggsave.path <- "/Users/rcphelps/code/thesis/ampelos/code/output/"

setwd("/Users/rcphelps/code/thesis/ampelos")

library(tidyverse)
library(dplyr)
library(knitr)
library(kableExtra)


```



```{r makeTibbles, echo=FALSE, include=TRUE, results='asis', message=F, warning=T}


# "weeks 23-25",  "weeks 26-31", "weeks 32-34"

source.url <- c("https://raw.githubusercontent.com/cordphelps/ampelos/master/data/bugs.csv")


bugs.tibl <- dplyr::as_tibble(read.csv(source.url, header=TRUE, row.names=NULL))

thomisidae.day.control.tbl <- bugs.tibl %>% 
  dplyr::filter(time == 'pm', transect=='control')  %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = 'pm',
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

thomisidae.night.control.tbl <- bugs.tibl %>% 
  dplyr::filter(time == 'am', transect=='control')  %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = 'am',
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

thomisidae.day.SNH.tbl <- bugs.tibl %>% 
  dplyr::filter(time == 'pm', transect=='oakMargin')  %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = 'pm',
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

thomisidae.night.SNH.tbl <- bugs.tibl %>% 
  dplyr::filter(time == 'am', transect=='oakMargin')  %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = 'am',
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

# **************************************************** #

thomisidae.period1.SNH.tibl <- bugs.tibl %>% 
  dplyr::filter(time == 'pm', transect=='oakMargin')  %>%
  dplyr::filter(week < 26) %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = time,
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

thomisidae.period1.control.tibl <- bugs.tibl %>% 
  dplyr::filter(time == 'pm', transect == 'control') %>%
  dplyr::filter(week < 26) %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = time,
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

thomisidae.period2.SNH.tibl <- bugs.tibl %>% 
  dplyr::filter(time == 'pm', transect=='oakMargin')  %>%
  dplyr::filter(week > 25 & week < 32) %>%
    dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = time,
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

thomisidae.period2.control.tibl <- bugs.tibl %>% 
  dplyr::filter(time == 'pm', transect == 'control') %>%
  dplyr::filter(week > 25 & week < 32) %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = time,
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

thomisidae.period3.SNH.tibl <- bugs.tibl %>% 
  dplyr::filter(time == 'pm', transect=='oakMargin')  %>%
  dplyr::filter(week > 31) %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = time,
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

thomisidae.period3.control.tibl <- bugs.tibl %>% 
  dplyr::filter(time == 'pm', transect == 'control') %>%
  dplyr::filter(week > 31) %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = time,
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

combo.period1.tibl <- bugs.tibl %>% 
  dplyr::filter(time != 'am') %>%
  dplyr::filter(week < 26)

combo.period2.tibl <- bugs.tibl %>% 
  dplyr::filter(time != 'am') %>%
  dplyr::filter(week > 25 & week < 32)

combo.period3.tibl <- bugs.tibl %>% 
  dplyr::filter(time != 'am') %>%
  dplyr::filter(week > 31)


```


```{r bugs, echo=FALSE, include=TRUE, results='asis', message=F, warning=F, out.width=c('50%', '50%'), fig.show='hold'}

bug.lst <- list()

bug.lst <- scanBugPercentages(bugs.tibl)

bug.lst <- createFamilyPercentages(bug.lst)

gg <- plotBugPercentages(bug.lst, spidersOnly=FALSE)

print(gg)

fileName <- "ggsave.insectPop.1.1.pdf"
if (file.exists(fileName)) { file.remove(fileName) }

ggsave(fileName, plot = gg, device = NULL, path = ggsave.path,
       scale = 1, width = 6, height = NA, dpi = 300, limitsize = TRUE,
       units = c("in", "cm", "mm"))

gg <- plotBugPercentages(bug.lst, spidersOnly=TRUE)

print(gg)

fileName <- "ggsave.insectPop.1.2.pdf"
if (file.exists(fileName)) { file.remove(fileName) }

ggsave(fileName, plot = gg, device = NULL, path = ggsave.path,
       scale = 1, width = 6, height = NA, dpi = 300, limitsize = TRUE,
       units = c("in", "cm", "mm"))

```

```{r cohensCalc, echo=FALSE, include=TRUE, results='asis', message=F, warning=T}

# include=FALSE : unable to suppress JGmisc::cohens.d output


# summary of estimators, standardizers, and recommended use
# table 1, "pooled SD" 
# https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3840331/
# cite:
# Lakens D. (2013). Calculating and reporting effect sizes to facilitate cumulative science: a practical primer for t-tests and ANOVAs. Frontiers in psychology, 4, 863. https://doi.org/10.3389/fpsyg.2013.00863

library(JGmisc)

period1.stats <- JGmisc::cohens.d(thomisidae.period1.SNH.tibl$totalSpiders, thomisidae.period1.control.tibl$totalSpiders)

period2.stats <- JGmisc::cohens.d(thomisidae.period2.SNH.tibl$totalSpiders, thomisidae.period2.control.tibl$totalSpiders)

period3.stats <- JGmisc::cohens.d(thomisidae.period3.SNH.tibl$totalSpiders, thomisidae.period3.control.tibl$totalSpiders)

################# for the hypothetical population
################# values used in the bayes analysis

trapEfficiency <- .1   

# for the purposes of evaluating the model (and calculating an effect likelihood)
# we suggest a hypothetical population (for each transect) which is the 
# SNH trapped mean divided by 'trap efficiency'
# (note that 'trap efficiency' does not have to be accurately known, we are just
# using it to generate a hypothetical population)

period1.hypoPopulation <- period1.stats$m1 / trapEfficiency 
period2.hypoPopulation <- period2.stats$m1 / trapEfficiency 
period3.hypoPopulation <- period3.stats$m1 / trapEfficiency 

#################
#################

```


```{r cohensStats, echo=FALSE, include=TRUE, results='asis', message=F, warning=T}


stats.tbl <- tribble(~period, ~cohens.d, ~SNHmean, ~controlMean,
                     "weeks 23-25", 
                     round(period1.stats$d,2), 
                     round(period1.stats$m1,2), 
                     round(period1.stats$m2,2),
                     "weeks 26-31", 
                     round(period2.stats$d,2), 
                     round(period2.stats$m1,2), 
                     round(period2.stats$m2,2),
                     "weeks 32-34", 
                     round(period3.stats$d,2), 
                     round(period3.stats$m1,2), 
                     round(period3.stats$m2,2)
                      )


# https://community.rstudio.com/t/sizing-tables-in-pdf-documents-using-knitr-and-kableextra/19285
  knitr::kable(stats.tbl, 
          caption="Comparison of SNH and control weekly daytime trapped\ncrab spider counts (Wilcoxon signed-rank test)",
          col.names = linebreak(c("seasonal period", 
                        "Cohen's d\neffect size", 
                        "SNH transect\nmean spiders per week\n(across 30 traps)", 
                        "control transect\nmean spiders per week\n(across 30 traps)")),
          escape=FALSE,
          align = "lccc",
          row.names=FALSE,
          format="latex", 
          booktabs=TRUE ) %>%
    
          kableExtra::column_spec(1,width = "1in") %>%
          kableExtra::column_spec(2,width = "1in") %>%
          kableExtra::column_spec(3,width = "1in") %>%
          kableExtra::column_spec(4,width = "1in") %>%
    
          kableExtra::save_kable(paste(ggsave.path, "table.cntlNight", ".pdf", sep=""))
  


# https://bookdown.org/yihui/rmarkdown-cookbook/kable.html#specify-column-alignment
  
  knitr::kable(stats.tbl, 
            caption="Comparison of SNH and control weekly daytime trapped\ncrab spider counts (Wilcoxon signed-rank test)",
            col.names = c("seasonal period", 
                          "Cohen's d<br/>effect size", 
                          "SNH transect<br/>mean spiders per week<br/>(across 30 traps)", 
                          "control transect<br/>mean spiders per week<br/>(across 30 traps)"
                          ),
            escape=FALSE,
            align = "lccc")

# New Effect Size Rules of Thumb
# Sawilowsky 2009
# https://digitalcommons.wayne.edu/cgi/viewcontent.cgi?referer=https://scholar.google.com/&httpsredir=1&article=1536&context=jmasm

# effect size, early season: d = 0.757   ('large' Cohen 1988)
# effect size, mid season:   d = 0.0348  ('very small' Sawilowsky, 2009)
# effect size, late season:  d = 0.299   ('small-medium' Cohen 1988)
#
# https://people.bath.ac.uk/pssiw/stats2/page2/page14/page14.html
# A large Cohen’s d doesn’t necessarily mean that an effect actually exists, 
# because Cohen’s d is just your best estimate of how big the effect is, 
# assuming it does exist.
#
# Nichols 2001 figure 4
# approx effect size, early season: (negative)
# approx effect size, mid season:   approx .5 'medium'
# approx effect size, late season:  approx .2 'small'
#
#
#

observations.daytime.period1 <- combo.period1.tibl %>% dplyr::group_by(julian) %>% count()
observations.daytime.period2 <- combo.period2.tibl %>% dplyr::group_by(julian) %>% count()
observations.daytime.period3 <- combo.period3.tibl %>% dplyr::group_by(julian) %>% count()

obs.period1 <- sum(observations.daytime.period1$n)
obs.period2 <- sum(observations.daytime.period2$n)
obs.period3 <- sum(observations.daytime.period3$n)


power.period1 <- pwr::pwr.t2n.test(n1 = obs.period1 / 2, 
                                   n2= obs.period1 / 2, 
                                   d = period1.stats$d, sig.level = 0.05, power = NULL)

power.period2 <- pwr::pwr.t2n.test(n1 = obs.period2 / 2, 
                                   n2= obs.period2 / 2, 
                                   d = period2.stats$d, sig.level = 0.05, power = NULL)

power.period3 <- pwr::pwr.t2n.test(n1 = obs.period3 / 2, 
                                   n2= obs.period3 / 2, 
                                   d = period3.stats$d, sig.level = 0.05, power = NULL)


stats.tbl <- tribble(~period, ~cohens.d, ~sig.level, ~power,  ~actualSampleSize,
                     "weeks 23-25", 
                     round(period1.stats$d,2), 
                     0.05, 
                     power.period1$n1,
                     round(power.period1$power, 2),
                     
                     "weeks 26-31", 
                     round(period2.stats$d,2), 
                     0.05, 
                     power.period2$n1,
                     round(power.period2$power, 2),
                     
                     "weeks 32-34", 
                     round(period3.stats$d,2), 
                     0.05, 
                     power.period3$n1,
                     round(power.period3$power, 2)
                      )

# https://community.rstudio.com/t/sizing-tables-in-pdf-documents-using-knitr-and-kableextra/19285
    
    knitr::kable(stats.tbl, 
               
          caption="power analysis by seasonal period: two sample t test",
          col.names = linebreak(c("seasonal period", 
                        "Cohen's d effect size\n(calculated)", 
                        "alpha\n(proposed)", 
                        "sample size\n(actual)",
                        "power\n(calculated)" 
                        )),
          escape=FALSE,
          align = "lcccc",
          row.names=FALSE,
          format="latex", 
          booktabs=TRUE ) %>%
    
          kableExtra::column_spec(1,width = "0.7in") %>%
          kableExtra::column_spec(2,width = "0.7in") %>%
          kableExtra::column_spec(3,width = "0.7in") %>%
          kableExtra::column_spec(4,width = "0.7in") %>%
          kableExtra::column_spec(4,width = "0.7in") %>%
    
          kableExtra::save_kable(paste(ggsave.path, "table.power", ".pdf", sep=""))
  

  
knitr::kable(stats.tbl, caption="power analysis by seasonal period: two sample t test",
             col.names = c("seasonal period", 
                           "Cohen's d<br/>effect size<br/>(calculated)", 
                           "alpha<br/>(proposed)", 
                           "sample size<br/>(actual)",
                           "power<br/>(calculated)" 
                           ),
             escape=FALSE,
             align = "lcccc")

```



```{r rawDistributions, echo=FALSE, include=TRUE, results="hide", message=F, warning=T, out.width=c('50%', '50%'), fig.show='hold' }

plotRawWeeklyV2(day=thomisidae.day.SNH.tbl, night=thomisidae.night.SNH.tbl, where="SNH")

plotRawWeeklyV2(day=thomisidae.day.control.tbl, night=thomisidae.night.control.tbl, where="control")


```



```{r wilcox-day-night, echo=FALSE, include=TRUE, results='asis', message=F, warning=T}

# compare day/night distributions for each transect

snh.stats <- wilcoxStats(vector1 = thomisidae.day.SNH.tbl, 
                         vector2 = thomisidae.night.SNH.tbl,
                         byTransect=FALSE)

control.stats <- wilcoxStats(vector1 = thomisidae.day.control.tbl,
                             vector2 = thomisidae.night.control.tbl,
                             byTransect=FALSE)

stats.tbl <- tribble(~transect, ~wilcox.p, ~effectSize, ~comment,
                     "SNH", round(snh.stats[[1]],3), 
                     round(snh.stats[[2]],3), 
                     snh.stats[[3]],
                     "control", round(control.stats[[1]],3), 
                     round(control.stats[[2]],3), 
                     control.stats[[3]]
                      )

  # https://community.rstudio.com/t/sizing-tables-in-pdf-documents-using-knitr-and-kableextra/19285
  knitr::kable(stats.tbl, 
               
          caption="Comparison of daylight and night-time weekly trapped\nspider counts by transect (Wilcoxon signed-rank test)",
          col.names = c("seasonal period", 
                        "p value", 
                        "effect metric", 
                        "effect magnitude"),
          align = "lccc",
          row.names=FALSE,
          format="latex", 
          booktabs=TRUE ) %>%
    
          kableExtra::column_spec(1,width = "1in") %>%
          kableExtra::column_spec(2,width = "1in") %>%
          kableExtra::column_spec(3,width = "1in") %>%
          kableExtra::column_spec(4,width = "1in") %>%
    
          kableExtra::save_kable(paste(ggsave.path, "table.dayNight", ".pdf", sep=""))
  

# https://bookdown.org/yihui/rmarkdown-cookbook/kable.html#specify-column-alignment
knitr::kable(stats.tbl, caption="Comparison of daylight and night-time weekly trapped\nspider counts by transect (Wilcoxon signed-rank test)",
             col.names = c("transect", 
                           "p value", 
                           "effect metric", 
                           "effect magnitude"),
             align = "lccc")

# rcp: "We conclude that the daylight and nighttime rates of trapped spiders are
# significantly different for both SNH and control transects. (p value = 0.01, 
# effect metric r = 0.4)"

```


```{r wilcox-SNH-control, echo=FALSE, include=TRUE, results='asis', message=F, warning=T}

# compare day/night distributions for each transect

period1.stats <- wilcoxStats(vector1 = thomisidae.period1.SNH.tibl, 
                         vector2 = thomisidae.period1.control.tibl, 
                         byTransect=TRUE)

period2.stats <- wilcoxStats(vector1 = thomisidae.period2.SNH.tibl, 
                         vector2 = thomisidae.period2.control.tibl, 
                         byTransect=TRUE)

period3.stats <- wilcoxStats(vector1 = thomisidae.period3.SNH.tibl, 
                         vector2 = thomisidae.period3.control.tibl, 
                         byTransect=TRUE)

stats.tbl <- tribble(~seasonalPeriod, ~wilcox.p, ~effectSize, ~comment,
                     "weeks 23-25", round(period1.stats[[1]],3), 
                     round(period1.stats[[2]],3), 
                     period1.stats[[3]],
                     "weeks 26-31", round(period2.stats[[1]],3), 
                     round(period2.stats[[2]],3), 
                     period2.stats[[3]],
                     "weeks 31-34", round(period3.stats[[1]],3), 
                     round(period3.stats[[2]],3), 
                     period3.stats[[3]]
                      )

  # output for pdf
  # https://community.rstudio.com/t/sizing-tables-in-pdf-documents-using-knitr-and-kableextra/19285
  knitr::kable(stats.tbl, 
               
          caption="Comparison of SNH and control weekly daytime trapped\nspider counts by seasonal period (Wilcoxon signed-rank test)",
          col.names = c("seasonal period", 
                        "p value", 
                        "effect metric", 
                        "effect magnitude"),
          
          align = "lccc",
          row.names=FALSE,
          format="latex", 
          booktabs=TRUE ) %>%
    
          kableExtra::column_spec(1,width = "1in") %>%
          kableExtra::column_spec(2,width = "1in") %>%
          kableExtra::column_spec(3,width = "1in") %>%
          kableExtra::column_spec(4,width = "1in") %>%
    
          kableExtra::save_kable(paste(ggsave.path, "table.SNHcontrol", ".pdf", sep=""))
  
  

# https://bookdown.org/yihui/rmarkdown-cookbook/kable.html#specify-column-alignment
knitr::kable(stats.tbl, caption="Comparison of SNH and control weekly daytime trapped\nspider counts by seasonal period (Wilcoxon signed-rank test)",
             col.names = c("seasonal period", 
                           "p value", 
                           "effect metric", 
                           "effect magnitude"),
             align = "lccc")




```


```{r densityPlots, echo=FALSE, include=TRUE, results="hide", message=F, warning=T, out.width=c('50%', '50%'), fig.show='hold' }


input.tibl <- combo.period1.tibl %>% mutate(transect=replace(as.character(transect), transect=='oakMargin', 'SNH')) %>% as_tibble()

densityNoFacets(tibble=input.tibl, periodString="weeks 23-25")
densityFacets(tibble=input.tibl, periodString="weeks 23-25")

input.tibl <- combo.period2.tibl %>% mutate(transect=replace(as.character(transect), transect=='oakMargin', 'SNH')) %>% as_tibble()

densityNoFacets(tibble=input.tibl, periodString="weeks 26-31")
densityFacets(tibble=input.tibl, periodString="weeks 26-31")

input.tibl <- combo.period3.tibl %>% mutate(transect=replace(as.character(transect), transect=='oakMargin', 'SNH')) %>% as_tibble()

print( densityNoFacets(tibble=input.tibl, periodString="weeks 32-34") )
print( densityFacets(tibble=input.tibl, periodString="weeks 32-34") )


```



```{r errorBars, echo=FALSE, include=TRUE, results="asis", message=F, warning=F, out.width=c('33%', '33%', '33%'), fig.show='hold'}

# calculate the mean and SE of traps (like Altieri)
# https://stackoverflow.com/questions/2676554/in-r-how-to-find-the-standard-error-of-the-mean
combo1.means.tibl <- combo.period1.tibl %>%
    dplyr::group_by(transect, positionX) %>%
    dplyr::summarize(mean = mean(Thomisidae..crab.spider., na.rm=TRUE),
              se = sd(Thomisidae..crab.spider., na.rm=TRUE) /
                    sqrt(length(position)),
              observations = n()
              )

combo2.means.tibl <- combo.period2.tibl %>%
    dplyr::group_by(transect, positionX) %>%
    dplyr::summarize(mean = mean(Thomisidae..crab.spider., na.rm=TRUE),
              se = sd(Thomisidae..crab.spider., na.rm=TRUE) /
                    sqrt(length(position)),
              observations = n()
              )

combo3.means.tibl <- combo.period3.tibl %>%
    dplyr::group_by(transect, positionX) %>%
    dplyr::summarize(mean = mean(Thomisidae..crab.spider., na.rm=TRUE),
              se = sd(Thomisidae..crab.spider., na.rm=TRUE) /
                    sqrt(length(position)),
              observations = n()
              )

# Two data samples are independent if they come from distinct populations and the samples do not affect each other. Using the Mann-Whitney-Wilcoxon Test, we can decide whether the population distributions are identical without assuming them to follow the normal distribution.
# http://www.r-tutor.com/elementary-statistics/non-parametric-methods/mann-whitney-wilcoxon-test

# wilcox.test(mean ~ transect, data=combo1.means.tibl, correct=FALSE)
# wilcox.test(mean ~ transect, data=combo2.means.tibl, correct=FALSE)
# wilcox.test(mean ~ transect, data=combo3.means.tibl, correct=FALSE)

# ***    'mean' shoud be OK    ***
# 2. If the data represent essentially discrete values (e.g. they
# are count data, or ordered categorical), where ties are intrinsically
# possible, then strictly speaking the Mann-Whitney test is not
# appropriate, since its distribution function depends on the assumption
# of continuity which is not true here.
# https://stat.ethz.ch/pipermail/r-help/2009-December/415767.html

# for more than 2 groups
# http://www.sthda.com/english/wiki/kruskal-wallis-test-in-r


errorBars(tibble=combo1.means.tibl, periodString = "weeks 23-25", observations = 27)

errorBars(tibble=combo2.means.tibl, periodString = "weeks 26-31", observations = 39)

errorBars(tibble=combo3.means.tibl, periodString = "weeks 32-34", observations = 27)



```


```{r bayes, echo=FALSE, include=TRUE, results="hide", message=F, warning=T, out.width=c('50%', '50%'), fig.show='hold'}


seed <- 101

# for each seasonal period
hypotheticalPopulation <- c(period1.hypoPopulation, 
                            period2.hypoPopulation, 
                            period3.hypoPopulation)
# hypotheticalPopulation <- c(58.13,15.93,6.67)



    # organize data into
    #       "week", "transect", "time", "cluster", "totalSpiders"
    # ( already done by evaluateDailySpiderCounts() )
    #

    #         existing models will be read from disc
    #         with TRUE/FALSE logic in generateLikelihoodV2() ......
    
    
    filtered.df <- bugs.tibl %>% 
      dplyr::filter(time != 'am') %>% 
      dplyr::group_by(week, transect) %>%
      dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.))
      
      # rename(totalSpiders = Thomisidae..crab.spider.)
    
    
    # read data from disc with fromDisc=TRUE
    # re-build brm model and posterior distribution with fromDisc=FALSE
    
    # compare predictions for a high contact and low contact vines
    
    gg.likelihood.pm.lst <- list()
    
    gg.likelihood.pm.lst <- generateLikelihoodV3(df=filtered.df,
              daytime='pm', fromDisc=TRUE, path= ggsave.path,
              randomSeed=seed, hp=hypotheticalPopulation)
    

```

```{r test, echo=FALSE, include=TRUE, results='asis', message=F, warning=T}

if (TRUE) {
  
  source('/Users/rcphelps/code/thesis/ampelos/code/bayesNoClusters.R')
  
  test.lst <- examineModelOutput(df=filtered.df,
              path= ggsave.path,
              daytime = 'pm',
              hp=hypotheticalPopulation)
  
  test.df <- test.lst[[4]] %>% as.data.frame()
  #max(test.df$lambda_high)
  #max(test.df$lambda_low)
  
  #period2.hypoPopulation
  #period3.hypoPopulation
  #hypotheticalPopulation
  
  
  stats.tbl <- tribble(~seasonalPeriod, 
                       ~hypoPop, 
                       ~modelHighContactMean,
                       ~modelLowContactMean,
                       
                     "weeks 23-25", 
                     round(period1.hypoPopulation, 0), 
                     round((mean(test.df$lambda_high) / period1.hypoPopulation) * 100, 1),
                     round((mean(test.df$lambda_low) / period1.hypoPopulation) * 100, 1),
                     
                     "weeks 26-31", 
                     round(period2.hypoPopulation, 0), 
                     round((mean(test.df$lambda_high.1) / period2.hypoPopulation) * 100, 1),
                     round((mean(test.df$lambda_low.1) / period2.hypoPopulation) * 100, 1),
                     
                     "weeks 31-34", 
                     round(period3.hypoPopulation, 0), 
                     round((mean(test.df$lambda_high.2) / period3.hypoPopulation) * 100, 1),
                     round((mean(test.df$lambda_low.2) / period3.hypoPopulation) * 100, 1)
                      )

  # https://bookdown.org/yihui/rmarkdown-cookbook/kable.html#specify-column-alignment
  
  # output for pdf
  # https://community.rstudio.com/t/sizing-tables-in-pdf-documents-using-knitr-and-kableextra/19285
  knitr::kable(stats.tbl, 
               
          caption="interaction model statistics for a hypothetical population by time period",
          col.names = linebreak(c("seasonal period", 
                        "population exposed to the traps\n(as an example)",
                        "SNH transect\nmodelled mean trapped spiders\n(percent)", 
                        "control transect\nmodelled mean trapped spiders\n(percent)" )),
          escape=FALSE,
          align = "lcccc",
          row.names=FALSE,
          format="latex", 
          booktabs=TRUE ) %>%
    
          kableExtra::column_spec(1,width = "1in") %>%
          kableExtra::column_spec(2,width = "1in") %>%
          kableExtra::column_spec(3,width = "1in") %>%
          kableExtra::column_spec(4,width = "1in") %>%
    
          # add_indent(c(2:3)) %>%
          # add_header_above(header="Header") %>%
          #footnote(c("Source; 2000 Census",
          #   "Source: 2010 Census",
          #   "Really long footnote that increases the width of the table.")) %>%
    
          kableExtra::save_kable(paste(ggsave.path, "table.1", ".pdf", sep=""))
  
  
    # output for markdown
    knitr::kable(stats.tbl, 
               
          caption="<b>interaction model statistics for a hypothetical population by time period</b>",
          col.names = c("seasonal period", 
                           "population<br/>exposed to the traps<br/>(as an example)",
                           "SNH transect<br/>modelled mean<br/>trapped spiders (percent)", 
                           "control transect<br/>modelled mean<br/>trapped spiders (percent)" ),
          escape=FALSE,
          align = "lcccc") 
  
}

```



```{r modelDiags, echo=FALSE, include=FALSE, results=FALSE, message=T, warning=T}


if (TRUE) {
  
    time <- "pm"
    
	  fullPath.rds <- paste(ggsave.path, "listV2-", time, ".rds", sep="")

    # read the 3 models from disc and run diags
	  gg.lst <- list()
    gg.lst <- modelDiagsV3(daytime = time, hp=hypotheticalPopulation, rds=fullPath.rds)

  }


```



```{r bayesPrimaryPlots, echo=FALSE, include=TRUE, results="hide", message=F, warning=T, out.width=c('50%', '50%'), fig.show='hold'}

    # just print the plausibility graph and distributions
    
    print(gg.likelihood.pm.lst[[1]])
      
    fileName <- paste("ggsave.plausibility.1.v2.pdf", sep="")
  
    if (file.exists(fileName)) { file.remove(fileName) }
      
    ggsave(fileName, 
              plot = gg.likelihood.pm.lst[[1]], 
              device = NULL, path = ggsave.path,
              scale = 1, width = 6, height = NA, dpi = 300, limitsize = TRUE,
              units = c("in", "cm", "mm"))

  
    print(gg.lst[[1]])
  
    fileName <- paste("ggsave.poisson.4.2.V2.pdf", sep="")
    
    ggsave.path <- "/Users/rcphelps/code/thesis/ampelos/code/output/"
      fullPath <- paste(ggsave.path, fileName, sep="")
  
      if (file.exists(fullPath)) { file.remove(fullPath) }

      ggsave(fileName, plot = gg.lst[[1]], 
              device = NULL, path = ggsave.path,
              scale = 1, width = 6, height = NA, dpi = 300, limitsize = TRUE,
              units = c("in", "cm", "mm"))
    
    

```



```{r posteriorGraphs, echo=FALSE, include=TRUE, results="hide", message=F, warning=T, out.width=c('33%', '33%', '33%'), fig.show='hold'}

# display the posterior graphs 

    for (i in 2:length(gg.likelihood.pm.lst)) {
    
      print(gg.likelihood.pm.lst[[i]])
      
      fileName <- paste("ggsave.plausibility.", i, ".v2.pdf", sep="")
  
      if (file.exists(fileName)) { file.remove(fileName) }
      
      ggsave(fileName, 
              plot = gg.likelihood.pm.lst[[i]], 
              device = NULL, path = ggsave.path,
              scale = 1, width = 6, height = NA, dpi = 300, limitsize = TRUE,
              units = c("in", "cm", "mm"))
      
    }
    

```


```{r printDiags2, echo=FALSE, include=TRUE, results="hide", message=F, warning=T, out.width=c('33%', '33%', '33%'), fig.show='hold'}

    for (i in 2:length(gg.lst)) {
  
      print(gg.lst[[i]])
  
      fileName <- paste("ggsave.poisson.", i, ".4.2.V2.pdf", sep="")
      ggsave.path <- "/Users/rcphelps/code/thesis/ampelos/code/output/"
      fullPath <- paste(ggsave.path, fileName, sep="")
  
      if (file.exists(fullPath)) { file.remove(fullPath) }

      ggsave(fileName, plot = gg.lst[[i]], 
              device = NULL, path = ggsave.path,
              scale = 1, width = 6, height = NA, dpi = 300, limitsize = TRUE,
              units = c("in", "cm", "mm"))
      
    }
```


```{r chi-squared, echo=FALSE, include=FALSE, results='asis', message=F, warning=T}

################ ignore: INSUFFICIENT SAMPLES and count magnitude (many zeros) FOR CHI_SQ
################
################

# The Coefficient of Variation is the ratio of the standard deviation to the mean. It is always dimensionless (i.e. it is a plain number without a unit) and is scale invariant (in other words, you can make changes to the length, height or other scale factors without it affecting the result).
# The Index of Dispersion is the ratio of the variance to the mean (hence the alternate name variance to mean ratio). I usually has a dimension (unless being applied to dimensionless counts) and it is not scale invariant.
# https://www.statisticshowto.com/index-of-dispersion/

# index of dispersion
# Practical Statistics for Field Biology. Fowler, Cohen, Jarvis
# Fowler, J., Cohen, L., & Jarvis, P. (1998). Practical statistics for field biology. Chichester: Wiley.
#
#



# with df=29 and chisq statistic > 50 the significance level is
# > 0.01. (appendix 3 ; Fowler, Cohen, Jarvis)

# rcp> We conclude that if the control transect spider counts are distributed 
# homogeneously, then a count difference of this magnitude would occur randomly 
# in fewer than 1% of equivalent surveys.

stats <- chiSqStats(thomisidae.period1.SNH.tibl, thomisidae.period1.control.tibl)

stats.tbl <- tribble(~transect, ~dispersionIndex, ~degreesFreedom, ~chiSq,
            "SNH", round(stats[[1]],3), round(stats[[2]],3), round(stats[[3]],3),
            "control", round(stats[[4]],3), round(stats[[5]],3), round(stats[[6]],3)
                      )

knitr::kable(stats.tbl, caption="INSUFFICIENT SAMPLES FOR CHI_SQ\nComparison of SNH and Control trapped\nspider totals by position (Chi Squared test)",
             col.names = c("transect", 
                           "dispersion index", 
                           "degrees of freedom", 
                           "chi squared"),
             align = "lccc")

```

