---
title: "ampelos V2"
output: 
 
 pdf_document: default
header-includes: 
  - \usepackage{caption}
    
 #always_allow_html: true
---

\captionsetup[table]{labelformat=empty, font=small}
always_allow_html: true

# https://stackoverflow.com/questions/45018397/changing-the-font-size-of-figure-captions-in-rmarkdown-html-output
<style>caption {font-size: 0.2em}</style>

```{css, echo = FALSE}

p.caption {
      font-weight: bold;
      font-size: 0.1em;
}
# https://stackoverflow.com/questions/34446139/caption-font-color-with-kable

```


```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = FALSE, results='hide')

# https://yihui.org/knitr/options/

# echo: (TRUE; logical or numeric) Whether to display the source code
# results: ('markup'; character) Controls how to display the text results.
# warning: (TRUE; logical) Whether to preserve warnings
# error: (TRUE; logical) Whether to preserve errors
# include: (TRUE; logical) Whether to include the chunk output in the output document.
# 
```

```{r localCode, echo=FALSE, include=FALSE}

################## pdf flag for save_kable() tables ##############

pdf.table <- TRUE

##################################################################

source('/Users/rcphelps/code/thesis/ampelos/code/bayesNoClusters.R')

ggsave.path <- "/Users/rcphelps/code/thesis/ampelos/code/output/"

setwd("/Users/rcphelps/code/thesis/ampelos")

library(tidyverse)
library(dplyr)
library(knitr)
library(kableExtra)

library(magick)
library(webshot)
# 


```



```{r makeTibbles, echo=FALSE, include=TRUE, results='asis', message=F, warning=T}


# "weeks 23-25",  "weeks 26-31", "weeks 32-34"

source.url <- c("https://raw.githubusercontent.com/cordphelps/ampelos/master/data/bugs.csv")


bugs.tibl <- dplyr::as_tibble(read.csv(source.url, header=TRUE, row.names=NULL))

thomisidae.day.control.tbl <- bugs.tibl %>% 
  dplyr::filter(time == 'pm', transect=='control')  %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = 'pm',
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

thomisidae.night.control.tbl <- bugs.tibl %>% 
  dplyr::filter(time == 'am', transect=='control')  %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = 'am',
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

thomisidae.day.SNH.tbl <- bugs.tibl %>% 
  dplyr::filter(time == 'pm', transect=='oakMargin')  %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = 'pm',
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

thomisidae.night.SNH.tbl <- bugs.tibl %>% 
  dplyr::filter(time == 'am', transect=='oakMargin')  %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = 'am',
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

# **************************************************** #

thomisidae.period1.SNH.tibl <- bugs.tibl %>% 
  dplyr::filter(time == 'pm', transect=='oakMargin')  %>%
  dplyr::filter(week < 26) %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = time,
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

thomisidae.period1.control.tibl <- bugs.tibl %>% 
  dplyr::filter(time == 'pm', transect == 'control') %>%
  dplyr::filter(week < 26) %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = time,
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

thomisidae.period2.SNH.tibl <- bugs.tibl %>% 
  dplyr::filter(time == 'pm', transect=='oakMargin')  %>%
  dplyr::filter(week > 25 & week < 32) %>%
    dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = time,
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

thomisidae.period2.control.tibl <- bugs.tibl %>% 
  dplyr::filter(time == 'pm', transect == 'control') %>%
  dplyr::filter(week > 25 & week < 32) %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = time,
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

thomisidae.period3.SNH.tibl <- bugs.tibl %>% 
  dplyr::filter(time == 'pm', transect=='oakMargin')  %>%
  dplyr::filter(week > 31) %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = time,
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

thomisidae.period3.control.tibl <- bugs.tibl %>% 
  dplyr::filter(time == 'pm', transect == 'control') %>%
  dplyr::filter(week > 31) %>%
  dplyr::group_by(julian, transect) %>%
  dplyr::summarize(totalSpiders = sum(Thomisidae..crab.spider.),
            time = time,
            week=week, transect=transect,
            .groups = 'drop') %>%
  dplyr::distinct()

combo.period1.tibl <- bugs.tibl %>% 
  dplyr::filter(time != 'am') %>%
  dplyr::filter(week < 26)

combo.period2.tibl <- bugs.tibl %>% 
  dplyr::filter(time != 'am') %>%
  dplyr::filter(week > 25 & week < 32)

combo.period3.tibl <- bugs.tibl %>% 
  dplyr::filter(time != 'am') %>%
  dplyr::filter(week > 31)


```


```{r cohensCalc, echo=FALSE, message=F, warning=T}

# include=FALSE : unable to suppress JGmisc::cohens.d output


# summary of estimators, standardizers, and recommended use
# table 1, "pooled SD" 
# https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3840331/
# cite:
# Lakens D. (2013). Calculating and reporting effect sizes to facilitate cumulative science: a practical primer for t-tests and ANOVAs. Frontiers in psychology, 4, 863. https://doi.org/10.3389/fpsyg.2013.00863

library(JGmisc)

# invisible(capture.output()) silences the verbose output of JGmisc::cohens.d()
# https://stackoverflow.com/questions/2723034/suppress-output-of-a-function/61571259#61571259

invisible({capture.output({

period1.stats <- JGmisc::cohens.d(thomisidae.period1.SNH.tibl$totalSpiders, thomisidae.period1.control.tibl$totalSpiders)

period2.stats <- JGmisc::cohens.d(thomisidae.period2.SNH.tibl$totalSpiders, thomisidae.period2.control.tibl$totalSpiders)

period3.stats <- JGmisc::cohens.d(thomisidae.period3.SNH.tibl$totalSpiders, thomisidae.period3.control.tibl$totalSpiders)

})})

################# for the hypothetical population
################# values used in the bayes analysis

trapEfficiency <- .1   

# for the purposes of evaluating the model (and calculating an effect likelihood)
# we suggest a hypothetical population (for each transect) which is the 
# SNH trapped mean divided by 'trap efficiency'
# (note that 'trap efficiency' does not have to be accurately known, we are just
# using it to generate a hypothetical population)

period1.hypoPopulation <- period1.stats$m1 / trapEfficiency 
period2.hypoPopulation <- period2.stats$m1 / trapEfficiency 
period3.hypoPopulation <- period3.stats$m1 / trapEfficiency 

#################
#################

```


```{r cohensStats, echo=FALSE, message=F, warning=T}


stats.tbl <- tribble(~period, ~cohens.d, ~SNHmean, ~controlMean,
                     "weeks 23-25", 
                     round(period1.stats$d,2), 
                     round(period1.stats$m1,2), 
                     round(period1.stats$m2,2),
                     "weeks 26-31", 
                     round(period2.stats$d,2), 
                     round(period2.stats$m1,2), 
                     round(period2.stats$m2,2),
                     "weeks 32-34", 
                     round(period3.stats$d,2), 
                     round(period3.stats$m1,2), 
                     round(period3.stats$m2,2)
                      )


```


```{r cohensFile, echo=FALSE, tab.cap = NULL, message=F, warning=T}

# tab.cap = NULL, results='asis', 


# https://community.rstudio.com/t/sizing-tables-in-pdf-documents-using-knitr-and-kableextra/19285


if (pdf.table==TRUE) {
  
  setwd("/Users/rcphelps/code/thesis/ampelos/") # due to save_kable() weirdness
  kable.path <- "code/output/"
  fileName <- paste(kable.path, "table.cntlNight.pdf", sep="")
  if (file.exists(fileName)) { file.remove(fileName) }
  
      knitr::kable(stats.tbl, 
          caption="SNH and control weekly daytime<br/>trapped crab spider counts<br/>(Wilcoxon signed-rank test)",
          #caption="<style=\'font-size: 10, text-align:right\'>new caption</style>",
          col.names = linebreak(c("seasonal<br/>period", 
                        "Cohen's d<br/>effect size", 
                        "SNH transect<br/>mean spiders per week", 
                        "control transect<br/>mean spiders per week")),
          escape=FALSE,
          align = "lccc",
          row.names=FALSE,
          format="html",
          booktabs=TRUE ) %>%
    
          kable_paper(html_font = "helvetica") %>%
          kableExtra::kable_styling(font_size = 10) %>%
          kableExtra::kable_styling(full_width = FALSE) %>%
    
          kableExtra::column_spec(1, width_max = "10%") %>%
          kableExtra::column_spec(2, width_max = "10%") %>%
          kableExtra::column_spec(3, width_max = "10%") %>%
          kableExtra::column_spec(4, width_max = "10%") %>%
  
          save_kable(fileName)
  
}
  
```
  
  

```{r powerStats, echo=FALSE, message=F, warning=T}

observations.daytime.period1 <- combo.period1.tibl %>% dplyr::group_by(julian) %>% count()
observations.daytime.period2 <- combo.period2.tibl %>% dplyr::group_by(julian) %>% count()
observations.daytime.period3 <- combo.period3.tibl %>% dplyr::group_by(julian) %>% count()

obs.period1 <- sum(observations.daytime.period1$n)
obs.period2 <- sum(observations.daytime.period2$n)
obs.period3 <- sum(observations.daytime.period3$n)


power.period1 <- pwr::pwr.t2n.test(n1 = obs.period1 / 2, 
                                   n2= obs.period1 / 2, 
                                   d = period1.stats$d, sig.level = 0.05, power = NULL)

power.period2 <- pwr::pwr.t2n.test(n1 = obs.period2 / 2, 
                                   n2= obs.period2 / 2, 
                                   d = period2.stats$d, sig.level = 0.05, power = NULL)

power.period3 <- pwr::pwr.t2n.test(n1 = obs.period3 / 2, 
                                   n2= obs.period3 / 2, 
                                   d = period3.stats$d, sig.level = 0.05, power = NULL)


stats.tbl <- tribble(~period, ~cohens.d, ~sig.level, ~power,  ~actualSampleSize,
                     "weeks 23-25", 
                     round(period1.stats$d,2), 
                     0.05, 
                     power.period1$n1,
                     round(power.period1$power, 2),
                     
                     "weeks 26-31", 
                     round(period2.stats$d,2), 
                     0.05, 
                     power.period2$n1,
                     round(power.period2$power, 2),
                     
                     "weeks 32-34", 
                     round(period3.stats$d,2), 
                     0.05, 
                     power.period3$n1,
                     round(power.period3$power, 2)
                      )

# https://community.rstudio.com/t/sizing-tables-in-pdf-documents-using-knitr-and-kableextra/19285
    
if (pdf.table==TRUE) {
  
  fileName <- paste(ggsave.path, "table.power", ".pdf", sep="")
  if (file.exists(fileName)) { file.remove(fileName) }
  
    knitr::kable(stats.tbl, 
               
          caption="power analysis by seasonal period: two sample t test",
          col.names = linebreak(c("seasonal period", 
                        "Cohen's d effect size\n(calculated)", 
                        "alpha\n(proposed)", 
                        "sample size\n(actual)",
                        "power\n(calculated)" 
                        )),
          escape=FALSE,
          align = "lcccc",
          row.names=FALSE,
          format="latex", 
          booktabs=TRUE ) %>%
    
          kableExtra::column_spec(1,width = "20%") %>%
          kableExtra::column_spec(2,width = "20%") %>%
          kableExtra::column_spec(3,width = "20%") %>%
          kableExtra::column_spec(4,width = "20%") %>%
          kableExtra::column_spec(5,width = "20%") %>%
    
          kableExtra::save_kable(fileName)
  
}
  

```




```{r wilcox-day-night, echo=FALSE, message=F, warning=T}

# compare day/night distributions for each transect

snh.stats <- wilcoxStats(vector1 = thomisidae.day.SNH.tbl, 
                         vector2 = thomisidae.night.SNH.tbl,
                         byTransect=FALSE)

control.stats <- wilcoxStats(vector1 = thomisidae.day.control.tbl,
                             vector2 = thomisidae.night.control.tbl,
                             byTransect=FALSE)

stats.tbl <- tribble(~transect, ~wilcox.p, ~effectSize, ~comment,
                     "SNH", round(snh.stats[[1]],3), 
                     round(snh.stats[[2]],3), 
                     snh.stats[[3]],
                     "control", round(control.stats[[1]],3), 
                     round(control.stats[[2]],3), 
                     control.stats[[3]]
                      )

if (pdf.table==TRUE) {
  
  fileName <- paste(ggsave.path, "table.dayNight", ".pdf", sep="")
  if (file.exists(fileName)) { file.remove(fileName) }
  
  # https://community.rstudio.com/t/sizing-tables-in-pdf-documents-using-knitr-and-kableextra/19285
  knitr::kable(stats.tbl, 
               
          caption="Comparison of daylight and night-time weekly trapped\nspider counts by transect (Wilcoxon signed-rank test)",
          col.names = c("seasonal period", 
                        "p value", 
                        "effect metric", 
                        "effect magnitude"),
          align = "lccc",
          row.names=FALSE,
          format="latex", 
          booktabs=TRUE ) %>%
    
          kableExtra::column_spec(1,width = "20%") %>%
          kableExtra::column_spec(2,width = "20%") %>%
          kableExtra::column_spec(3,width = "20%") %>%
          kableExtra::column_spec(4,width = "20%") %>%
    
          kableExtra::save_kable(fileName)
  
  }
  


```


```{r wilcox-SNH-control, echo=FALSE, message=F, warning=T}

# compare day/night distributions for each transect

period1.stats <- wilcoxStats(vector1 = thomisidae.period1.SNH.tibl, 
                         vector2 = thomisidae.period1.control.tibl, 
                         byTransect=TRUE)

period2.stats <- wilcoxStats(vector1 = thomisidae.period2.SNH.tibl, 
                         vector2 = thomisidae.period2.control.tibl, 
                         byTransect=TRUE)

period3.stats <- wilcoxStats(vector1 = thomisidae.period3.SNH.tibl, 
                         vector2 = thomisidae.period3.control.tibl, 
                         byTransect=TRUE)

stats.tbl <- tribble(~seasonalPeriod, ~wilcox.p, ~effectSize, ~comment,
                     "weeks 23-25", round(period1.stats[[1]],3), 
                     round(period1.stats[[2]],3), 
                     period1.stats[[3]],
                     "weeks 26-31", round(period2.stats[[1]],3), 
                     round(period2.stats[[2]],3), 
                     period2.stats[[3]],
                     "weeks 31-34", round(period3.stats[[1]],3), 
                     round(period3.stats[[2]],3), 
                     period3.stats[[3]]
                      )

if (pdf.table==TRUE) {
  
  fileName <- paste(ggsave.path, "table.SNHcontrol", ".pdf", sep="")
  if (file.exists(fileName)) { file.remove(fileName) }
    
  # output for pdf
  # https://community.rstudio.com/t/sizing-tables-in-pdf-documents-using-knitr-and-kableextra/19285
  knitr::kable(stats.tbl, 
               
          caption="Comparison of SNH and control weekly daytime trapped\nspider counts by seasonal period (Wilcoxon signed-rank test)",
          col.names = c("seasonal period", 
                        "p value", 
                        "effect metric", 
                        "effect magnitude"),
          
          align = "lccc",
          row.names=FALSE,
          format="latex", 
          booktabs=TRUE ) %>%
    
          kableExtra::column_spec(1,width = "20%") %>%
          kableExtra::column_spec(2,width = "20%") %>%
          kableExtra::column_spec(3,width = "20%") %>%
          kableExtra::column_spec(4,width = "20%") %>%
    
          kableExtra::save_kable(fileName)
  
}


```





```{r test, echo=FALSE, message=F, warning=T, tab.cap = NULL}

if (TRUE) {
  
  source('/Users/rcphelps/code/thesis/ampelos/code/bayesNoClusters.R')
  
  test.lst <- examineModelOutput(df=filtered.df,
              path= ggsave.path,
              daytime = 'pm',
              hp=hypotheticalPopulation)
  
  test.df <- test.lst[[4]] %>% as.data.frame()
  
  like.df <- test.lst[[5]]
  
  #max(test.df$lambda_high)
  #max(test.df$lambda_low)
  
  #period2.hypoPopulation
  #period3.hypoPopulation
  #hypotheticalPopulation
  
  
  stats.tbl <- tribble(~seasonalPeriod, 
                       ~likelihood,
                       ~hypoPop, 
                       ~modelHighContactMean,
                       ~modelLowContactMean,
                       
                     "weeks 23-25", 
                     round(like.df$plausibility[[1]] * 100 , 1),
                     round(period1.hypoPopulation, 0), 
                     round((mean(test.df$lambda_high) / period1.hypoPopulation) * 100, 1),
                     round((mean(test.df$lambda_low) / period1.hypoPopulation) * 100, 1),
                     
                     "weeks 26-31", 
                     round(like.df$plausibility[[2]] * 100 , 1),
                     round(period2.hypoPopulation, 0), 
                     round((mean(test.df$lambda_high.1) / period2.hypoPopulation) * 100, 1),
                     round((mean(test.df$lambda_low.1) / period2.hypoPopulation) * 100, 1),
                     
                     "weeks 31-34", 
                     round(like.df$plausibility[[3]] * 100 , 1),
                     round(period3.hypoPopulation, 0), 
                     round((mean(test.df$lambda_high.2) / period3.hypoPopulation) * 100, 1),
                     round((mean(test.df$lambda_low.2) / period3.hypoPopulation) * 100, 1)
                      )

  # https://bookdown.org/yihui/rmarkdown-cookbook/kable.html#specify-column-alignment
  
if (pdf.table==TRUE) {
  
  fileName <- paste(ggsave.path, "table.1", ".pdf", sep="")
  if (file.exists(fileName)) { file.remove(fileName) }
  
  # output for pdf
  # https://community.rstudio.com/t/sizing-tables-in-pdf-documents-using-knitr-and-kableextra/19285
  knitr::kable(stats.tbl, 
               
          caption="interaction model statistics for a hypothetical population by time period",
          col.names = linebreak(c("seasonal period", 
                        "positive SNH effect\nplausibility\n(percent)",
                        "population exposed to the traps\n(example)",
                        "SNH mean\ntrapped spiders\n(percent)", 
                        "control mean\ntrapped spiders\n(percent)" )),
          escape=FALSE,
          align = "lcccc",
          row.names=FALSE,
          format="latex", 
          booktabs=TRUE ) %>%

          # remove_table_numbers %>%
    
          kableExtra::column_spec(1,width = "20%") %>%
          kableExtra::column_spec(2,width = "20%") %>%
          kableExtra::column_spec(3,width = "20%") %>%
          kableExtra::column_spec(4,width = "20%") %>%
          kableExtra::column_spec(5,width = "20%") %>%
    
          # add_indent(c(2:3)) %>%
          # add_header_above(header="Header") %>%
          #footnote(c("Source; 2000 Census",
          #   "Source: 2010 Census",
          #   "Really long footnote that increases the width of the table.")) %>%
    
          kableExtra::save_kable(fileName)
  
  
  }
  
}

```


