

generateLikelihoodV3 <- function(df, daytime, fromDisc, path, randomSeed,  hp) {


  ##
  ##
  ## build a df of likelihood (the probability that the
  ## spider population is influenced by the oakMargin) by cluster by week
  ## UPDATE ELEMENT 5 of the inbound list (a list of 9 likelihoods) and 
  ## returning the new list.
  ##
  ## save a text file summary() of each model to disc
  ##
  ## return a plot the likelihoods
  ##
  ## return plots of the mcmc_intervals for 9 models
  ##

  ## parameter df is the 4th member of the output of evaluateDailySpiderCounts(bugs.df)

  ## parameter inboundList is the output of evaluateDailySpiderCounts(bugs.df)

  ## parameter hp is the hypotheticalPopulation used to generate likelihood

  
  if("rethinking" %in% (.packages())){
     detach("package:rethinking", unload=TRUE) 
  }
  
  # https://bookdown.org/connect/#/apps/1850/access
  library(brms)
  library(rstan)
  #For execution on a local, multicore CPU with excess RAM we recommend calling
  options(mc.cores = parallel::detectCores())
  #To avoid recompilation of unchanged Stan programs, we recommend calling
  rstan_options(auto_write = TRUE)

  fileName.rds <- paste(path, "listV2-", daytime, ".rds", sep="")

  inboundList <- list()


  if (fromDisc==TRUE) {   # read the structure from disk

    inboundList <- readRDS(fileName.rds)

    likelihood.df <- inboundList[[5]] 
    modelInput <- inboundList[[7]]        # a list of the 9 data sources
    modelOutput <- inboundList[[8]]       # a list of the 9 models
    label.list <- inboundList[[9]]        # 
    post.df.list <- inboundList[[10]]     # a list of the 9 posterior distributions


  } else {   # go through the tedious process of creating the brm models

  
    ## total.df ( = df) , generated by evaluateDailySpiderCounts()
    ##                    'am' plus 'pm' data per 'timeList <- c('am', 'pm')'
    ##
    ## multiple records per week with columns
    ## week, transect, time, cluster, totalSpiders
    ##
  
    # estimate different mean populations across 3 groups of weeks reflecting the 
    # seasonal population decline
    # 
    # week 23, 24, 25           : mean 75, sd 15
    # week 26, 27, 28, 29, 30   : mean 50, sd 8
    # week 31, 32, 33, 34       : mean 15, sd 2
    
    
    
    likelihood.df <- NULL
    modelInput <-list()
    post.df.list <- list()
    modelOutput <- list()

  
    cl.st.list <- list()  # for each cluster  
    # build list of dataframes represting the seasonal population 
    # plus a variable log-population
    #
    label.list <- list()  # remember which cluster and seasonal timeframe
    label.list[[1]] <- "seasonal timeframe: one"
    label.list[[2]] <- "seasonal timeframe: two"
    label.list[[3]] <- "seasonal timeframe: three"


    #
    # lists containing parameters developed in evaluateDailySpiderCounts()
    # 
    # 34 observations of 8 variables
    # week, transect, time, cluster, totalSpiders, population, log_pop, contact_high
    #
    #
    # mean population for 9 models     :  inboundList[[11]]            
    #  
  
    cl.st.list[[1]] <- df %>% dplyr::filter(week < 26)
    cl.st.list[[1]]$population <- hp[[1]]  
    cl.st.list[[1]]$log_pop <- log(cl.st.list[[1]]$population)  # R code 10.40
    cl.st.list[[1]]$contact_high <- ifelse( cl.st.list[[1]]$transect=="oakMargin" , 1 , 0 )
    
    cl.st.list[[2]] <- df %>% dplyr::filter(week > 25 & week < 31)
    cl.st.list[[2]]$population <- hp[[2]]  
    cl.st.list[[2]]$log_pop <- log(cl.st.list[[2]]$population)  # R code 10.40
    cl.st.list[[2]]$contact_high <- ifelse( cl.st.list[[2]]$transect=="oakMargin" , 1 , 0 )
    
    cl.st.list[[3]] <- df %>% dplyr::filter(week > 30)
    cl.st.list[[3]]$population <- hp[[3]]  
    cl.st.list[[3]]$log_pop <- log(cl.st.list[[3]]$population)  # R code 10.40
    cl.st.list[[3]]$contact_high <- ifelse( cl.st.list[[3]]$transect=="oakMargin" , 1 , 0 )
    
  
    
    #### model building ####
    #### model building ####
    #### model building ####
    for (i in 1:length(cl.st.list)) {  # build model for each seasonal timeframe

      # ref: Oceanic Tool Complexity Model
      # https://bookdown.org/connect/#/apps/1850/access 
    
        
        b10.10 <-
          brm(data = cl.st.list[[i]], family = poisson,
              totalSpiders ~ 1 + log_pop + contact_high + contact_high:log_pop,  # yes, + contact_high:log_pop
              prior = c(prior(normal(0, 100), class = Intercept),
                        prior(normal(0, 1), class = b)),
             iter = 3000, warmup = 1000, chains = 4, cores = 4, seed = randomSeed)

        #print(b10.10)

        modelInput[[i]] <- cl.st.list[[i]]
        modelOutput[[i]] <- b10.10
      

        post.df.list[[i]] <- brms::posterior_samples(modelOutput[[i]])  # 


        # adjust hypothetical population by seasonal timeframe 
        if (i == 1)  {
          hPop <- hp[[1]]
          seasonalTimeframe <- "one"
        } else if (i == 2) {
          hPop <- hp[[2]]
          seasonalTimeframe <- "two"
        } else {
          hPop <- hp[[3]]
          seasonalTimeframe <- "three"
        }  


 
        temp.df <- post.df.list[[i]] %>%   
          mutate(lambda_high = exp(b_Intercept + b_contact_high + (b_log_pop + `b_log_pop:contact_high`) * log(hPop) ),
                 lambda_low  = exp(b_Intercept + b_log_pop * log(hPop) ) ) %>% 
          mutate(diff        = lambda_high - lambda_low) 
        
        like.df <- temp.df %>%
          summarise(sum = sum(diff > 0)/length(diff))  # 
        
       
    
      temp2.df <- data.frame(seasonalTimeframe, like.df$sum) 
      # column names need to match for rbind() to work
      names(temp2.df) <- c("seasonalTimeframe", "plausibility")
    
      # tack it on
      if (!exists('likelihood.df')) {
        likelihood.df <- temp2.df
        # (so, on the first pass the column names are cool)
      } else {
        likelihood.df <- rbind(likelihood.df, temp2.df)
      }
    
    }  
    #### end model building ####
    #### end model building ####
    #### end model building ####

    
    
    if (file.exists(fileName.rds)) { file.remove(fileName.rds) }

    inboundList[[5]] <- likelihood.df
    inboundList[[7]] <- modelInput  # that is a list of the 9 data sources
    inboundList[[8]] <- modelOutput  # that is a list of the 9 models
    inboundList[[9]] <- label.list  # 
    inboundList[[10]] <- post.df.list

    saveRDS(inboundList, fileName.rds)

    } 



    # print(inboundList[[5]])
    ggList <- list()
    # plot the likelihood for the 9 models
    ggList[[1]] <- plotLikelihoodV2(tibble=as_tibble(likelihood.df),  hypoPop=hp,
                                  	cap=paste("daytime: ", daytime, sep=""))

    library(bayesplot)

    for (i in 1:3) {

      fileName.txt <- paste(path, "clBRMsummary-v2-", daytime, "-", i, ".txt", sep="")
      if (file.exists(fileName.txt)) file.remove(fileName.txt)

      sink(file=fileName.txt, append = TRUE, type = "output")
      print(writeLines(paste("generateLikelihoodV3()               ", "  i= ", i, sep="")))  # Sys.time(), 
        
      print(summary(modelOutput[[i]], prob=.89))
      sink(NULL)

    }

    # print the posterior graphs separately so that the color can be adjusted to math the cluster info

    color_scheme_set("red")     # setting used by bayesplot mcmc_intervals()  

    index <- c(1,2,3)           # cluster 'one'

    for (i in index) {

      # plot the posterior distributions
      ggList[[i+1]] <- post.df.list[[i]] %>%

      select(-lp__) %>% 
      rename(b_interaction = `b_log_pop:contact_high`) %>%

      bayesplot::mcmc_intervals(prob = .5, prob_outer = .89) +
      theme(axis.ticks.y = element_blank(),
        axis.text.y  = element_text(hjust = 0)) +
      theme_bw() +
      ggplot2::labs(
        caption = paste("posterior distribution coefficient plot\nmedians with 50% and 89% credible intervals",
                        " ; seasonal timeframe: ", "one?", 
                        "\ninteraction plausibility: ", "round(likelihood.df[[3]][[1]],2)", sep="")
                    )
    }


  
      # reserved positions:
    # returnList[[1]]) # scatter plot by cluster with seasonal timeframes
    # returnList[[2]]) # scatter plot by am/pm
    # returnList[[3]]) # scatter plot by transect
    #
    # returnList[[4]] is the dataframe used for the graphics (total.df)
    # from bayes.R evaluateDailySpiderCounts()
    # it is raw, not averaged, bugs.df data transformed to : 
    #          ("week", "transect", "time", "cluster", "totalSpiders")
    #
    # returnList[[5]] <- likelihood.df
    # returnList[[6]]                   # likelihood by cluster with seasonal timeframes
    # returnList[[7]] <- modelInput     # that is a list of the 9 data sources
    # returnList[[8]] <- modelOutput    # that is a list of the 9 models
    # returnList[[9]] <- label.list     # 
  


    # cleanup

    rm(inboundList)
    rm(likelihood.df)
    rm(modelInput)
    rm(modelOutput)
    rm(label.list)
    rm(post.df.list)

    detach("package:rstan", unload=TRUE)  
    detach("package:bayesplot", unload=TRUE)
    detach("package:brms", unload=TRUE) 

  
    return(ggList)
  
}




plotLikelihoodV2 <- function(tibble, hypoPop, cap) {
  
  # input df :
  # cluster{one, two, three}, seasonalTimeframe{one, two, three}, plausibility(decimal)
  #

  
  colours = c("three" = "blue", "two" = "green", "one" = "red")
  
  gg <- ggplot(tibble, aes(x=seasonalTimeframe, y=plausibility)) +
    
        geom_jitter(aes(fill = "green"), shape = 21, size=5, show.legend=TRUE, width=0.05) +
    
    	ylim(c(0, 1)) + 
    	expand_limits(y=c(0,1)) + 
 
    	labs(y="plausibility", 
         x="seasonal timeframe", 
         caption = paste("the 'plausibility' of an SNH effect on the crab spider population\n", 
                          "for a hypothetical vine population of ", 
                          hypoPop[[1]], " / ", hypoPop[[2]], " / ", hypoPop[[3]] , " spiders\n",
                          cap, sep="") ) +
    
    	scale_x_discrete(labels=c("one" = "weeks\n23-25", "two" = "weeks\n26-31", "three" = "weeks\n32-34"),
    					limits=c("one", "two", "three")) +
    
    	coord_fixed(1.5) + # control the aspect ratio of the output
    
    	theme_bw() +

    	theme(legend.position="none") 
  
  
  
  
  return(gg)
  
  
}

getRDS <- function() {

	# > five <- getRDS()
	# [1] "./code/output/listV2-pm.rds"
	# > five[[5]]
  	#	seasonalTimeframe plausibility
	# 1               one     0.029625
	# 2               two     0.468875
	# 3             three     0.763375
	# >

	setwd("/Users/rcphelps/code/thesis/ampelos")
	path <- "./code/output/"
	daytime <- "pm"

	fileName.rds <- paste(path, "listV2-", daytime, ".rds", sep="")

	print(fileName.rds)

	dataFromDisc <- list()
	# read the structure from disk

    dataFromDisc <- readRDS(fileName.rds)

    likelihood.df <- dataFromDisc[[5]] 
    modelInput <- dataFromDisc[[7]]        # a list of the 9 data sources
    modelOutput <- dataFromDisc[[8]]       # a list of the 9 models
    label.list <- dataFromDisc[[9]]        # 
    post.df.list <- dataFromDisc[[10]]     # a list of the 9 posterior distributions

    return(dataFromDisc)

}


modelDiagsV3 <- function(daytime, hp, rds) {


  prev.lst <- list()
  prev.lst <- readRDS(rds)

  post.df.lst <- list()
  post.df.lst <- prev.lst[[10]] 

  modelOutput.lst <- list()
  modelOutput.lst <- prev.lst[[8]]       # a list of the 3 models




  for (j in 1:3) {   

    # adjust hypothetical population by seasonal timeframe 
    if (j == 1) {
      hPop <- hp[[1]]
    } else if (j == 2) {
      hPop <- hp[[2]]
    } else {
      hPop <- hp[[3]]
    }  

    post.df.lst[[j]] <- post.df.lst[[j]] %>%   
          mutate(trappedSpiders_high = exp(b_Intercept + b_contact_high + (b_log_pop + `b_log_pop:contact_high`) * log(hPop) ),
                 trappedSpiders_low  = exp(b_Intercept + b_log_pop * log(hPop) )) %>% 
          #mutate(diff        = (trappedSpiders_high - trappedSpiders_low) / trappedSpiders_low )
          mutate(diff        = trappedSpiders_high - trappedSpiders_low) 

      names(post.df.lst[[j]])[names(post.df.lst[[j]])=='b_contact_high'] <- 'bc'
      names(post.df.lst[[j]])[names(post.df.lst[[j]])=='b_log_pop:contact_high'] <- 'bpc'

  }

  gg.lst <- list()

  # insert seasonal period flag into the data

  gg.lst[[1]] <- plotPosteriorDensityV2(t1 = as_tibble(post.df.lst[[1]] %>% mutate(period="1")), 
  										t2 = as_tibble(post.df.lst[[2]] %>% mutate(period="2")), 
  										t3 = as_tibble(post.df.lst[[3]] %>% mutate(period="3"))
    									)

  gg.lst[[2]] <- justJitterPlotV2(t1 = as_tibble(post.df.lst[[1]] %>% mutate(period="1")))
  gg.lst[[3]] <- justJitterPlotV2(t1 = as_tibble(post.df.lst[[2]] %>% mutate(period="2")))
  gg.lst[[4]] <- justJitterPlotV2(t1 = as_tibble(post.df.lst[[3]] %>% mutate(period="3")))


  gg.models.lst <- modelComparisonV2(models=modelOutput.lst, daytime='pm', randomSeed=seed, debug=FALSE)

  gg.lst[[5]] <- gg.models.lst[[1]]
  gg.lst[[6]] <- gg.models.lst[[2]]
  gg.lst[[7]] <- gg.models.lst[[3]]


  gg.mcmc.lst <- list()
  gg.mcmc.lst <- modelMCMCcheckV2(models=modelOutput.lst, daytime=time, debug=FALSE)

  gg.lst[[8]] <- gg.mcmc.lst[[1]]
  gg.lst[[9]] <- gg.mcmc.lst[[2]]
  gg.lst[[10]] <- gg.mcmc.lst[[3]]



  return(gg.lst)

}



plotPosteriorDensityV2 <- function(t1, t2, t3) {

    colours = c("1" = "red", "2" = "green", "3" = "blue")

    gg <- ggplot() + 
   
    geom_density(data=t1, aes(x=diff, y=..scaled.., fill = period), alpha=.7, show.legend=TRUE, key_glyph = "dotplot") +
    geom_density(data=t2, aes(x=diff, y=..scaled.., fill = period), alpha=.7, show.legend=TRUE, key_glyph = "dotplot") +
    geom_density(data=t3, aes(x=diff, y=..scaled.., fill = period), alpha=.7, show.legend=TRUE, key_glyph = "dotplot") +

    # stat_density(aes(x=diff), geom="point") +   # there is some magic here to adjust legend shapes
    # https://stackoverflow.com/questions/46597079/change-the-shape-of-the-legend-in-density-plots-with-ggplot2
    
    geom_vline(xintercept=0) + #
    
    
    coord_cartesian(ylim=c(0, 1.1), xlim=c(-1.3, 1.3))  + # clip
    #coord_cartesian(ylim=c(0, 1.5), xlim=c(-3, 5))  + # clip

    scale_y_continuous(breaks = seq(min(0), max(1.5), by = .2)) +

    labs(y="density", 
         x="trapped Thomisidae rate\nSNH treatment compared to control (daylight hours)", 
         caption = paste("the distribution of the plausible\ndifference in the average rate of\ntrapped Thomisidae", sep="") ) +
    
    theme_bw() +

    scale_fill_manual(values = colours, 
                      breaks = c("1", "2", "3"),
                      labels = c("week 23-25", "week 26-30", "week 31-34")) +
    guides(shape = guide_legend(override.aes = list(shape = 21))) +  # define the shape presented in the legend

    
    theme(legend.title = element_blank(),
          legend.spacing.y = unit(0, "mm"), 
          legend.justification=c(1,0),
          panel.border = element_rect(colour = "black", fill=NA),
          aspect.ratio = 1, axis.text = element_text(colour = 1, size = 12),
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black")) 

    return(gg)

}


justJitterPlotV2 <- function(t1) {

	colours = c("1" = "red", "2" = "green", "3" = "blue")

    gg <- ggplot() + 

    geom_jitter(data=t1, aes(x=bc, y=bpc, fill = period), shape=21, size=2, alpha=.3, 
      show.legend=TRUE) +

      # ggplot2 issue # 3460 
      # https://github.com/tidyverse/ggplot2/issues/3460
      # show.legend=TRUE, key_glyph = draw_key_dotplot(data=data.frame(), size=5)) +

    guides(fill = guide_legend(override.aes = list(size = 5, alpha = 1))) + 
    
    scale_y_continuous(breaks = seq(min(0), max(2), by = 1)) +
    scale_x_continuous(breaks=seq(-15,5,5)) + 
    
    labs(y="bpc", 
         x="bc", 
         caption = paste("the joint posterior distribution of bc and bpc", sep="") ) +
    
    theme_bw() +

    scale_fill_manual(values = colours, 
                      breaks = c("1", "2", "3"),
                      labels = c("week 23-25", "week 26-30", "week 31-34")) +

    scale_shape_manual(values = 21) +
    
    theme(legend.title = element_blank(),
          legend.spacing.y = unit(0, "mm"), 
          legend.justification=c(1,0),
          panel.border = element_rect(colour = "black", fill=NA),
          aspect.ratio = 1, axis.text = element_text(colour = 1, size = 12),
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black")) 

    return(gg)

}



modelComparisonV2 <- function(models, daytime, randomSeed, debug) {

  # Statistical Rethinking, code 10.45 and Statistical Rethinking Recoded

  library(brms)
  library(rstan)
  library(Rcpp)   # brms bug: avoids  
                  #         Error in cpp_object_initializer(.self, .refClassDef, ...) 
                  #         could not find function "cpp_object_initializer"
                  #         failed to create the sampler; sampling not done

  #For execution on a local, multicore CPU with excess RAM we recommend calling
  options(mc.cores = parallel::detectCores())
  #To avoid recompilation of unchanged Stan programs, we recommend calling
  rstan_options(auto_write = TRUE)


  noInteraction <- list()
  noContact <- list()
  noLogPop <- list()
  onlyIntercept <- list()
  gg.lst <- list()

  cl <- c("one", "two", "three")
  st <- c("weeks 23-25", "weeks 26-31", "weeks 32-34")
  cluster <- NULL
  timeframe <- NULL


  for (i in 1:length(models)) { 

    # logic from https://bookdown.org/connect/#/apps/1850/access

    # no interaction
    noInteraction[[i]] <- update(models[[i]], formula = totalSpiders ~ 1 + log_pop + contact_high)

    # no contact rate
    noContact[[i]] <- update(models[[i]], formula = totalSpiders ~ 1 + log_pop)

    # no log-population
    noLogPop[[i]] <- update(models[[i]], formula = totalSpiders ~ 1 + contact_high)

    # intercept only
    onlyIntercept[[i]] <- update(models[[i]], formula = totalSpiders ~ 1, seed=randomSeed)

    models[[i]]   <- brms::add_criterion(models[[i]], criterion = "waic")
    noInteraction[[i]] <- brms::add_criterion(noInteraction[[i]], criterion = "waic")
    noContact[[i]]     <- brms::add_criterion(noContact[[i]], criterion = "waic")
    noLogPop[[i]]      <- brms::add_criterion(noLogPop[[i]], criterion = "waic")
    onlyIntercept[[i]] <- brms::add_criterion(onlyIntercept[[i]], criterion = "waic")


    w <- brms::loo_compare(models[[i]], noInteraction[[i]], noContact[[i]], noLogPop[[i]], onlyIntercept[[i]], criterion = "waic")

    cbind(waic_diff = w[, 1] * -2, se= w[, 2] *  2) %>% 
    round(digits = 2)
 

    # detect seasonal timeframe 
    if ( i == 1 ) {
      timeframe <- st[[1]]
      color <- "red"
    } else if ( i == 2 ) {
      timeframe <- st[[2]]
      color <- "green"
    } else {
      timeframe <- st[[3]]
      color <- "blue"
    }  


    gg.lst[[i]] <- w %>% data.frame() %>% 
          tibble::rownames_to_column(var = "model") %>%
 
          ggplot(aes(x = reorder(model, -waic), 
                 y    = waic,
                 ymin = waic - se_waic,   # 4x "standard error" ~= 95% confidence interval
                 ymax = waic + se_waic
                 #color = model)) +
                 )) +
          theme_bw() +
          geom_pointrange(shape = 21, size=1, fill=color, show.legend = F) + 
          coord_flip() +
          labs(x = NULL, y = NULL,
                caption = paste("Watanabe-Akaike Information Criterion\n+/- the standard error\nseasonal timeframe: ", 
                  timeframe, ")", sep="") ) +
          theme(axis.ticks.y    = element_blank())


    if (debug) {
      break
    }


  }


  # cleanup

  rm(noInteraction)
  rm(noContact)
  rm(noLogPop)
  rm(onlyIntercept)

  detach("package:brms", unload=TRUE) 
  detach("package:rstan", unload=TRUE) 


  return(gg.lst)

}


modelMCMCcheckV2 <- function(models, daytime, debug) {

  # ref: https://www.rensvandeschoot.com/brms-wambs/
  # BRMS Tutorial: Applying the WAMBS – checklist
  #
  library(tidyr)
  library(brms)
  library(ggmcmc)
  library(mcmcplots) 

  # For execution on a local, multicore CPU with excess RAM we recommend calling
  options(mc.cores = parallel::detectCores())

  gg.lst <- list()


  # l2. Does the trace-plot exhibit convergence?


  for (i in 1:length(models)) { 

    modeltransformed <- ggmcmc::ggs(models[[i]]) # the ggs function transforms the BRMS output into a longformat tibble, 
                                            # that we can use to make different types of plots.

    gg.lst[[i]] <- ggplot(filter(modeltransformed, Parameter==c("b_Intercept", "b_log_pop", "b_contact_high", "b_log_pop:b_contact_high"), 
                                  Iteration>1000), aes(x=Iteration, y=value, col=as.factor(Chain))) +
                            geom_line() +
                            theme_bw() +
                            facet_grid(Parameter ~ .,scale='free_y',switch = 'y') +
                            labs(caption=paste("mcmc chains caterpillar plot\n", "i= ", i, sep=""), col= "chains")

    if (debug) {
      break
    }

  }

  # cleanup

  detach("package:brms", unload=TRUE) 
  detach("package:ggmcmc", unload=TRUE) 
  detach("package:mcmcplots", unload=TRUE) 


  return(gg.lst)

}

