---
title: "CIMIS"
output: github_document
---

```{r, echo=F, message=F, warning=F}
# read CIMIS data via the public API and plot results
## 
## http://et.water.ca.gov/Rest/Index
  
# stuff you need
#
#   1) a CIMIS API key (see http://et.water.ca.gov/Home/Faq)
#   2) write the key to disk in json format:
#        {
#        "CIMIS-API-KEY": "b7aaaaff-zzzz-yyyy-xxxx-4ab4bbbb1b8"
#        }
#   3) adjust the startDate, endDate, and station per your requirements
  
library(jsonlite)
library(gridExtra)
library(cowplot)

source("bug-library.R")

if (FALSE) {
  cimisKey <- fromJSON("./PRIVATE-CIMIS-API-KEY.json")
  baseURL <- "http://et.water.ca.gov/api/data?appKey="
  key <- cimisKey[["CIMIS-API-KEY"]] 
  station <- "&targets=231"
  start <- "&startDate=2018-01-01"
  end <- "&endDate=2018-08-30"
  #end <- paste("&endDate=", Sys.Date(), sep="")
  units <- "&unitOfMeasure=M"
  # units <- "&unitOfMeasure=E"   # default = english units
  
  apiString <- paste(baseURL, key, station, start, end, units, sep="")
  print(apiString)
  
  data <- fromJSON(apiString)   # CIMIS appears to be throttling requests.....
  data.df <- as.data.frame(data)
  df2.df <- as.data.frame(data.df$Data.Providers.Records)
  
  
  write.csv(jsonlite::flatten(df2.df), './weather/CIMIS231.csv')
  
} else {    # read data saved to disc to avoid
            # multiple hits to the CIMIS db
  
  df2.df <- read.csv("./weather/CIMIS231.csv")
  
}
  

#
# CIMIS data items : http://et.water.ca.gov/Rest/Index
# 
df2.df$DayPrecip <- as.numeric(df2.df$DayPrecip.Value)
df2.df$DayAirTmpAvg <- as.numeric(df2.df$DayAirTmpAvg.Value)
df2.df$DayAirTmpMin <- as.numeric(df2.df$DayAirTmpMin.Value)
df2.df$DayAirTmpMax <- as.numeric(df2.df$DayAirTmpMax.Value)
df2.df$DaySoilTmpAvg <- as.numeric(df2.df$DaySoilTmpAvg.Value)
df2.df$DayRelHumAvg <- as.numeric(df2.df$DayRelHumAvg.Value)
df2.df$DayWindSpdAvg <- as.numeric(df2.df$DayWindSpdAvg.Value)
df2.df$julian <- as.numeric(df2.df$Julian)

# convert more vars as necessary

assign("df2.df", df2.df, envir=.GlobalEnv)
  
```

```{r cimis, echo=F, message=T, warning=T}
library(ggplot2)
library(dplyr)

ambient231 <- ggplot(data = df2.df, aes(x=julian)) + 
  
  geom_point(aes(y = DayAirTmpMax, colour = "max"), shape=21) +
  geom_point(aes(y = DayAirTmpAvg, colour = "avg"), shape=21) +
  geom_point(aes(y = DayAirTmpMin, colour = "min"), shape=21) +
  
  geom_smooth(data = df2.df, aes(x=julian, y = DayAirTmpMax), method="loess", se=FALSE, col="red") +
  geom_smooth(data = df2.df, aes(x=julian, y = DayAirTmpAvg), method="loess", se=FALSE, col="green") +
  geom_smooth(data = df2.df, aes(x=julian, y = DayAirTmpMin), method="loess", se=FALSE, col="blue") +
  
  scale_colour_manual("daily \ntemperatures",
          values=c(max="red", avg="green", min="blue"),
          labels = c(max="maximum", avg="average", min="minimum")) +   # manual legend
  
  geom_vline(xintercept=152, linetype="dotted", alpha=.75) +  # june 1
  geom_vline(xintercept=182, linetype="dotted", alpha=.75) +  # july 1
  geom_vline(xintercept=213, linetype="dotted", alpha=.75) +  # august 1
  
  geom_label(aes(x = 152, y = -2, label = "1 June")) +
  geom_label(aes(x = 182, y = 0, label = "1 July")) +
  geom_label(aes(x = 213, y = -2, label = "1 August")) +
  
  ylim(-10,40) +
  scale_y_continuous(breaks=seq(-10,40,5), 
                       sec.axis = sec_axis(~.*(9/5) + 32,
                                           breaks= seq(0, 110, 10),
                                           name= "air temp (F)"))  +
  
  labs(title = paste("2018 Ambient Temperatures", sep=""), 
      subtitle = paste("CIMIS Station #231, Lompoc, California", sep=""),
      x = "julian day", y = "air temp (C)") +

  theme_bw() +
  theme(axis.title.y.right = element_text(angle = 90)) 
# +
#  theme(legend.position="bottom")



temp.df <- df2.df %>% dplyr::filter(DayPrecip>0)
  
precip231 <- ggplot(data = temp.df, aes(x=julian, y=DayPrecip)) + 
  
  geom_point(shape=21) +
  geom_smooth(method="loess", se=FALSE, col="blue") +
  
  geom_vline(xintercept=152, linetype="dotted", alpha=.75) +  # june 1
  geom_vline(xintercept=182, linetype="dotted", alpha=.75) +  # july 1
  geom_vline(xintercept=213, linetype="dotted", alpha=.75) +  # august 1
  
  geom_label(aes(x = 152, y = 3, label = "1 June")) +
  geom_label(aes(x = 182, y = 3, label = "1 July")) +
  geom_label(aes(x = 213, y = 3, label = "1 August")) +
  
  scale_y_continuous(breaks=seq(0,100,10))  +
  xlim(0,250) +
  labs(x = "julian day", y = "precipitation (mm)") +
  labs(title= paste("2018 Average Precipitation", sep=""), 
         subtitle = paste("CIMIS Station #231, Lompoc, California", sep="")) +
   
  theme_bw() +
  theme(legend.position="none")

  
  
humidity231 <- ggplot(data = df2.df, aes(x=julian, y=DayRelHumAvg)) + 
  # geom_line(aes(y = DayRelHumAvg), colour = "blue") +
  geom_point(shape=21) + 
  geom_smooth(method="loess", se=FALSE, col="blue") +  
  
  geom_vline(xintercept=152, linetype="dotted", alpha=.75) +  # june 1
  geom_vline(xintercept=182, linetype="dotted", alpha=.75) +  # july 1
  geom_vline(xintercept=213, linetype="dotted", alpha=.75) +  # august 1
  
  geom_label(aes(x = 152, y = 12, label = "1 June")) +
  geom_label(aes(x = 182, y = 12, label = "1 July")) +
  geom_label(aes(x = 213, y = 12, label = "1 August")) +
  
  #geom_vline(xintercept=175) +  # stylet oil
  # ylim(-10,40) +
  scale_y_continuous(breaks=seq(0,100,10))  +
  labs(x = "julian day", y = "average relative humidity (%)") +
  labs(title= paste("2018 Average Relative Humidity", sep=""), 
         subtitle = paste("CIMIS Station #231, Lompoc, California", sep="")) +
   
  theme_bw() +
  theme(legend.position="none")


ground231 <- ggplot(data = df2.df, aes(x=julian, y=DaySoilTmpAvg)) + 
  geom_point(shape=21) + 
  geom_smooth(method="loess", se=FALSE, col="blue") + 
  
  geom_vline(xintercept=152, linetype="dotted", alpha=.75) +  # june 1
  geom_vline(xintercept=182, linetype="dotted", alpha=.75) +  # july 1
  geom_vline(xintercept=213, linetype="dotted", alpha=.75) +  # august 1
  
  geom_label(aes(x = 152, y = 10, label = "1 June")) +
  geom_label(aes(x = 182, y = 10, label = "1 July")) +
  geom_label(aes(x = 213, y = 10, label = "1 August")) +
  
  ylim(0,40) +
  expand_limits(y = 40) +
  #scale_y_continuous(breaks=seq(0,40,10),
  scale_y_continuous(breaks=seq(0,40,10),
    sec.axis = sec_axis(~.*(9/5) + 32,
                        breaks= seq(0, 110, 10),
                        name= "temp (F)")) +
  labs(x = "julian day", y = "temp (C)") +
  labs(title = paste("2018 Average Soil Temperature 15 cm below soil surface", sep=""), 
        subtitle = paste("CIMIS Station #231, Lompoc, California", sep=""),
        caption=paste("sensor located under irrigated grass", sep="") )  +
  theme_bw() +
  theme(axis.title.y.right = element_text(angle = 90)) +
  theme(legend.position="none")



wind231 <- ggplot(data = df2.df, aes(x=julian, y=DayWindSpdAvg)) + 
  geom_point(shape=21) + 
  geom_smooth(method="loess", se=FALSE, col="blue") +  
  
  geom_vline(xintercept=152, linetype="dotted", alpha=.75) +  # june 1
  geom_vline(xintercept=182, linetype="dotted", alpha=.75) +  # july 1
  geom_vline(xintercept=213, linetype="dotted", alpha=.75) +  # august 1
  
  geom_label(aes(x = 152, y = 0, label = "1 June")) +
  geom_label(aes(x = 182, y = 0, label = "1 July")) +
  geom_label(aes(x = 213, y = 0, label = "1 August")) +

  ylim(0,10) +
  expand_limits(y = 10) +
  # scale_y_continuous(breaks=seq(0,40,10),
  scale_y_continuous() +
  labs(x = "julian day", y = "meters/second") +
  labs(title = paste("2018 Average Wind Speed", sep=""), 
        subtitle = paste("CIMIS Station #231, Lompoc, California", sep=""),
        caption=paste("", sep="") )  +
  theme_bw() +
  theme(axis.title.y.right = element_text(angle = 90)) 



```

```{r, ambient}
print(ambient231)

```


```{r, precip}

print(precip231)

```

```{r, humidity}

print(humidity231)

```


```{r, ground}

print(ground231)

```


```{r, wind}

print(wind231)
```


