---
title: "ampelos"
output: github_document
---


```{r, echo=F, message=F, warning=F}
                                    # , out.height = '100%'}
# county map

# get the coordinates of a place
# https://support.google.com/maps/answer/18539?co=GENIE.Platform%3DDesktop&hl=en


# http://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html
# install.packages(c("ggplot2", "devtools", "dplyr", "stringr"))
# install.packages(c("maps", "mapdata"))
# devtools::install_github("dkahle/ggmap")

library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(gridExtra)
library(cowplot)    # height adjustment in tables with plot_grid()
library(patchwork)  # alternative to cowplot
library(egg)        # alternative to cowplot


states <- map_data("state")
west_coast <- subset(states, region %in% c("california", "oregon", "washington"))

#> west_coast
#long      lat group order     region
#667   -120.0060 42.00927     4   667 california
#668   -120.0060 41.20139     4   668 california
#669   -120.0060 39.70024     4   669 california

westCoast <- ggplot(data = west_coast) + 
  geom_polygon(aes(x = long, y = lat, group = group), fill = "palegreen", color = "black") +
  coord_fixed(1.3) +
  theme_bw()

ca_df <- subset(states, region == "california")
counties <- map_data("county")
ca_county <- subset(counties, region == "california")
sbCounty <- subset(counties, subregion == "santa barbara")

vC <- subset(counties, subregion == "ventura")
sloC <- subset(counties, subregion == "san luis obispo")
bC <- subset(counties, subregion == "san benito")
# cC <- subset(counties, subregion == "santa cruz")  # data looks wrong
mC <- subset(counties, subregion == "monterey")
centralCoast <- dplyr::bind_rows(vC, sloC, bC, mC)



california <- ggplot(data = ca_df, mapping = aes(x = long, y = lat, group = group)) + 
  
  geom_polygon(color = "black", fill = "#F4D292") + 
  #geom_polygon(data = ca_county, fill = "paleblue", color = "black") +
  geom_polygon(data = centralCoast, fill = "#E79798", color = "black") +
  geom_polygon(color = "black", fill = NA) +  # get the state border back on top
  geom_polygon(data = sbCounty, 
               aes(x = long, y = lat, group = group), 
               fill = 'palegreen', color = "black") +   # "palegreen"

  coord_fixed(1.3) +  # aspect ratio for lon/lat
  expand_limits(y = c(33, 42), x = c(-125,-114)) +
  
  labs(title="California 'Central Coast'\nCounties",
       subtitle=paste("Santa Barbara County in green\n", " \n", " ", sep=""),  # match plot sub-title space
          x="longitude", 
          y="latitude", 
          caption = paste(" ", sep="") )  +
  
  #theme_nothing() +
  theme_bw()  + # default font size = 12pt
                # https://stackoverflow.com/questions/24874594/font-size-confusion-in-ggplot2

  theme(plot.subtitle=element_text(size=9))  # must follow theme_bw() to override default

  #theme(plot.background = element_rect(fill = "green")) # works with plot_grid(), not patchwork
  #theme(panel.background = element_rect(fill = "red"))



```




```{r, echo=F, message=F, warning=F}


sbbox <- make_bbox(lon = sbCounty$long, lat = sbCounty$lat, f = .3)
sq_map <- get_map(location = sbbox, maptype = "satellite", source = "google")

# CIMIS #231 google map-able coordinates : 34.672222, -120.51306
# Ampelos 34.625133, -120.280478
bbPoints.df <-dplyr::tribble(~name, ~lon, ~lat, 
                           "corner1", -121, 34.3,
                           "corner2", -119, 35.3)

placePoints.df <-dplyr::tribble(~name, ~lon, ~lat, 
                           "CIMIS-231", -120.51306, 34.672222, 
                           "Ampelos", -120.280478, 34.625133)

ampelosPoint.df <-dplyr::tribble(~name, ~lon, ~lat, 
                           "Ampelos", -120.280478, 34.625133)

center <- sapply(bbPoints.df[2:3], mean)

sbbox <- make_bbox(lon = bbPoints.df$lon, lat = bbPoints.df$lat, f = 1)
    # f = number specifying the fraction by which the range should be extended
# maptype =  "terrain"
  
sq_map <- get_map(location = center, maptype = "satellite", source = "google", zoom=9)


```


```{r, echo=F, message=F, warning=F}


ampelosOnly <- ggmap(sq_map) + 
  geom_point(data = ampelosPoint.df, mapping = aes(x = lon, y = lat), 
             color = "green", shape=13, size = 8, stroke=2) +
  geom_label(data = ampelosPoint.df, aes(label = paste(as.character(name), sep="")), 
            angle = 0, hjust = 0, nudge_x = 0.06, nudge_y = 0.08) +
  
  coord_fixed(1.3) +  # aspect ratio for lon/lat
  expand_limits(y=c(34.3,35.3)) +
  scale_y_continuous(breaks=seq(34.3,35.3,.5)) +
  expand_limits(x=c(-121, -119)) +
  scale_x_continuous(breaks=seq(-121, -119, 1)) +
  
  labs(title="Ampelos Vineyards\nin the Sta. Rita Hills AVA",
          x="longitude", 
          y="latitude", 
          caption = paste(" ", sep="") ) +
  
  theme_bw() +  # default font size = 12pt
                # https://stackoverflow.com/questions/24874594/font-size-confusion-in-ggplot2
  #theme(axis.text=element_text(size=10),axis.title=element_text(size=10))
  
  theme(plot.subtitle=element_text(size=9))  # must follow theme_bw() to override default



CIMISampelos <- ggmap(sq_map) + 
  geom_point(data = placePoints.df, mapping = aes(x = lon, y = lat), 
             color = "green", shape=13, size = 8, stroke=2) +
  geom_label(data = placePoints.df, aes(label = paste(as.character(name), sep="")), 
            angle = 0, hjust = 0, nudge_x = 0.06, nudge_y = 0.08) +
  
  coord_fixed(1.3) +  # aspect ratio for lon/lat
  expand_limits(y=c(34.3,35.3)) +
  scale_y_continuous(breaks=seq(34.3,35.3,.5)) +
  expand_limits(x=c(-121, -119)) +
  scale_x_continuous(breaks=seq(-121, -119, 1)) +
  
  labs(title="relative locations: Ampelos Vineyards\nand CIMIS weather station #231",
        subtitle=paste("14 miles (22 Km) between",
                          "\nCIMIS #231 at 34:40:19.9986 N, 120:30:47.0154 W",
                          "\nand Ampelos at 34:37:30.4782 N, 120:16:49.7208 W", sep=""),   
          x="longitude", 
          y="latitude", 
          caption = paste("https://www.nhc.noaa.gov/gccalc.shtml",
                          sep="") ) +
  
  # "\nhttps://www.fcc.gov/media/radio/dms-decimal",
  
  theme_bw() +  # default font size = 12pt
                # https://stackoverflow.com/questions/24874594/font-size-confusion-in-ggplot2
  #theme(axis.text=element_text(size=10),axis.title=element_text(size=10))
  
  theme(plot.subtitle=element_text(size=9))  # must follow theme_bw() to override default




```


```{r, echo=F, message=F, warning=F}

sq_map <- get_map(location = center, maptype = "satellite", source = "google", zoom=13)

ampelosZoom <- ggmap(sq_map) + 
  geom_point(data = ampelosPoint.df, mapping = aes(x = lon, y = lat), 
             color = "green", shape=13, size = 8, stroke=2) +
  geom_label(data = ampelosPoint.df, aes(label = paste(as.character(name), sep="")), 
            angle = 0, hjust = 0, nudge_x = 0.06, nudge_y = 0.08) +
  
  coord_fixed(1.3) +  # aspect ratio for lon/lat
  expand_limits(y=c(34.3,35.3)) +
  scale_y_continuous(breaks=seq(34.3,35.3,.5)) +
  expand_limits(x=c(-121, -119)) +
  scale_x_continuous(breaks=seq(-121, -119, 1)) +
  
  labs(title="Ampelos Vineyards\nin the Sta. Rita Hills AVA",
          x="longitude", 
          y="latitude", 
          caption = paste(" ", sep="") ) +
  
  theme_bw() +  # default font size = 12pt
                # https://stackoverflow.com/questions/24874594/font-size-confusion-in-ggplot2
  #theme(axis.text=element_text(size=10),axis.title=element_text(size=10))
  
  theme(plot.subtitle=element_text(size=9))  # must follow theme_bw() to override default




```




```{r, echo=F, message=F, warning=F}

if (TRUE) {
  
  #grid.arrange(westCoast, california, ncol=2, nrow=1)
  plot_grid(california, ampelosOnly,
          align = "h",
          ncol = 2,
          rel_heights = c(1,1),
          rel_widths = c(1,1)
          )

  # it is difficult to adjust the space between plots with plot_grid()
  # https://github.com/wilkelab/cowplot/issues/31
  # 
  
}

```



```{r, echo=F, message=F, warning=F}

if (TRUE) {
  
  #grid.arrange(westCoast, california, ncol=2, nrow=1)
  plot_grid(CIMISampelos, ampelosZoom,
          align = "h",
          ncol = 2,
          rel_heights = c(1,1),
          rel_widths = c(1,1)
          )

  # it is difficult to adjust the space between plots with plot_grid()
  # https://github.com/wilkelab/cowplot/issues/31
  # 
  
}


```

```{r, echo=F, message=F, warning=F}

if (FALSE) {
california + 
  patchwork::plot_spacer() + 
  patchwork::plot_layout(ncol=3, 
                         heights = c(1,1,1), 
                         widths = c(1, 0.5, 2)) +
  CIMISampelos
}

```


```{r, echo=F, message=F, warning=F}

if (FALSE) {
library(grid)
pushViewport(viewport(layout=grid.layout(1,2)))
print(california,vp=viewport(layout.pos.row=1,layout.pos.col=1))
print(CIMISampelos,vp=viewport(layout.pos.row=1,layout.pos.col=2))
}

```



```{r, echo=F, message=F, warning=F}

if (FALSE) {
# https://cran.r-project.org/web/packages/egg/vignettes/Overview.html

mapGrob <- lapply(list(california, CIMISampelos), expose_layout, FALSE, FALSE)
grid.arrange(
  grobs = mapGrob,
  widths = c(1, 1),
  heights = c(1,1),
  layout_matrix = rbind( c(1, 2)),
  set_panel_size(debug=TRUE)
)
}

```

