---
title: "ampelos model check"
output: github_document
---


```{r setup, echo=FALSE, include=FALSE, message=F, warning=F}

setwd("/Users/rcphelps/code/thesis/ampelos")

source("./code/bug-library.R")
source("./code/similarity.R")
source("./code/jaccard-similarity.R")
source("./code/diversity.R")
source("./code/k-means.R")
source("./code/clusterSimilarity.R")
source('./code/bayes.R')
source('./code/ranking.R')

# library(ampelos)   <-- failed replacement for sample.int, 
# see bayes.R likelihoodPlusModelDiags()

source.url <- c("https://raw.githubusercontent.com/cordphelps/ampelos/master/data/bugs.csv")
bugs.df <- read.csv(source.url, header=TRUE, row.names=NULL)


```



```{r results = 'asis' }

# build the likelihood data : generateLikelihoodV2() 
returnList <- evaluateDailySpiderCounts(bugs.df)
  
# returnList[[4]] is the data 'dataframe' used for the graphics (total.df)
# from bayes.R evaluateDailySpiderCounts()

rl <- returnList
## rl[[4]] is multiple records per week with columns
## week, transect, time, cluster, totalSpiders

setwd("/Users/rcphelps/code/thesis/ampelos")
getwd()

filtered.df <- rl[[4]] %>% dplyr::filter(time == 'pm')
# read models from disc
models.list <- generateLikelihoodV2models(df=filtered.df, inboundList=rl, daytime='pm')



```




```{r results = 'asis' }

# ref: https://www.rensvandeschoot.com/brms-wambs/
# BRMS Tutorial: Applying the WAMBS – checklist
#

library(brms)
library(ggmcmc)
library(mcmcplots) 

get_prior(b_Intercept ~ 1 + b_log_pop + b_contact_high + b_contact_high:b_log_pop, data=as.data.frame(models.list[[1]]))



```



```{r results = 'asis' }

# l2. Does the trace-plot exhibit convergence?

modeltranformed<-ggs(models.list[[1]]) # the ggs function transforms the BRMS output into a longformat tibble, that we can use to make different types of plots.

ggplot(filter(modeltranformed, Parameter==c("b_Intercept", "b_log_pop", "b_contact_high", "b_log_pop:b_contact_high"), Iteration>1000), aes(x=Iteration, y=value, col=as.factor(Chain))) +
  geom_line() +
  facet_grid(Parameter ~ .,scale='free_y',switch = 'y') +
  labs(title="Caterpillar Plots", col= "Chains")



```


```{r results = 'asis' }

# To obtain convergence diagnostics to check convergence for the parameters of interest we use the Gelman and Rubin diagnostic (Gelman and Rubin 1992) and the Geweke (1992) diagnostic.

modelposterior<-as.mcmc(models.list[[1]]) # with the as.mcmc() command we can use all the CODA package convergence statistics and plotting options
gelman.diag(modelposterior[, 1:5])

gelman.plot(modelposterior[, 1:5])

```


```{r results = 'asis' }

# 4. Does the posterior distribution histogram have enough information?

plot(hypothesis(models.list[[1]], "log_pop = 0"), plot = F, theme = theme_get())[[1]]+ scale_x_continuous(limits=c(-5, 5))

```


```{r results = 'asis' }

# 5. Do the chains exhibit a strong degree of autocorrelation?

autocorr.diag(modelposterior[,1:5], lags = c(0, 1,2,3,4, 5, 10, 50))

```


```{r results = 'asis' }

# 6. Do the posterior distributions make substantive sense?

model <- models.list[[1]]

ggplot(filter(modeltranformed, Parameter==c("b_log_pop","b_contact_high"), Iteration>1000), aes(x=value, fill=Parameter)) +
  geom_density(alpha=.5) +
  geom_vline(xintercept = 0, col="red", size=1) +
  scale_x_continuous(name="Value", limits=c(-3, 3)) + 
    geom_vline(xintercept = summary(model)$fixed[1,3:4], col="darkgreen", linetype=2) +
    geom_vline(xintercept = summary(model)$fixed[2,3:4], col="blue", linetype=2) +
    geom_vline(xintercept = summary(model)$fixed[3,3:4], col="red", linetype=2) +
  theme_light() +
   scale_fill_manual(name='Parameters', values = c("red","darkgreen" , "lightblue"), labels=c(expression( " "  ~  gamma[Exraversion]), expression( " "  ~  gamma[Intercept]),  expression( " "  ~  gamma[Sex]))) +
  labs(title="Posterior Density of Parameters With 95% CCI lines (1)")


```



```{r results = 'asis' }

# 10. Is the Bayesian way of interpreting and reporting model results used?

# For a summary on how to interpret and report models, please refer to https://www.rensvandeschoot.com/bayesian-analyses-where-to-start-and-what-to-report/

# Dear rc.phelps Thanks for your email! Yes, I agree with McElreath that this is not the best statement. I actually very much like the approach of Kruschke: http://www.indiana.edu/~kruschke/articles/Kruschke2011PoPScorrected.pdf
#Hope this helps! Rens Prof. Dr. Rens van de Schoot - Department of Methodology & Statistics – Faculty of Social and Behavioral Sciences - Utrecht University –  The Netherlands  - Member Young Academy of the Royal Dutch Academy of Science Office:  Sjoerd Groenman building A105 – Email: a.g.j.vandeschoot@uu.nl –  Homepage: www.rensvandeschoot.com

summary(model)

```


```{r results = 'asis' }

# long text tables

# "column spec"
# https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html

```
